from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.colors import grey  
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image  
)
def add_footer(canvas, doc):
    canvas.saveState()

    canvas.setStrokeColor(grey)
    canvas.line(40, 35, 555, 35)

    canvas.setFont("Helvetica", 9)

    canvas.drawString(
        40,
        20,
        "Generated by AI Workforce Assistant | Visionary InfoTech Pvt. Ltd."
    )

    canvas.drawRightString(
        555,
        20,
        f"Page {doc.page}"
    )

    canvas.restoreState()

def generate_pdf(question, summary, dataframe=None):
    """
    Generates a professional HRBP PDF report.

    Parameters
    ----------
    question : str
        User question

    summary : str
        AI summary

    dataframe : pandas.DataFrame
        Optional analytics table

    Returns
    -------
    BytesIO
        PDF buffer
    """

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.fontSize = 22
    title_style.spaceAfter = 6

    heading_style = styles["Heading2"]
    heading_style.fontSize = 15
    heading_style.spaceBefore = 12
    heading_style.spaceAfter = 8

    normal_style = styles["BodyText"]
    normal_style.fontSize = 11
    normal_style.leading = 18

    story = []

    # =====================================================
    # COMPANY LOGO
    # =====================================================

    try:
        logo = Image("assets/logo.png")
        logo.drawHeight = 0.8 * inch
        logo.drawWidth = 0.8 * inch
        logo.hAlign = "CENTER"

        story.append(logo)
        story.append(Spacer(1, 0.10 * inch))

    except:
        pass

    # =====================================================
    # TITLE
    # =====================================================

    story.append(
        Paragraph(
            "Visionary InfoTech Pvt. Ltd.",
            title_style
        )
    )

    story.append(
        Paragraph(
            "AI Workforce Assistant",
            heading_style
        )
    )

    story.append(
        Paragraph(
            "<b>Executive Workforce Analytics Report</b>",
            normal_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # =====================================================
    # DATE
    # =====================================================

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d %b %Y %I:%M %p')}",
            normal_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # =====================================================
    # QUESTION
    # =====================================================

    story.append(
        Paragraph(
            "<b>User Question</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            question,
            normal_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # =====================================================
    # SUMMARY
    # =====================================================

    story.append(
        Paragraph(
            "<b>AI Executive Summary</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            summary.replace("\n", "<br/>"),
            normal_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # =====================================================
    # TABLE
    # =====================================================

    if dataframe is not None:

        story.append(
            Paragraph(
                "<b>Analytics Table</b>",
                heading_style
            )
        )

        table_data = [list(dataframe.columns)]

        for row in dataframe.values.tolist():
            table_data.append(row)

            table = Table(
            table_data,
            repeatRows=1
        )

        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F4C81")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 11),

                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                    ("TOPPADDING", (0, 0), (-1, 0), 10),

                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 1), (-1, -1), 10),

                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ]
            )
        )
        story.append(table)

    doc.build(
    story,
    onFirstPage=add_footer,
    onLaterPages=add_footer
)

    buffer.seek(0)

    return buffer